### ISSUE TITLE
NUT beacon gets undetected after pairing

### ISSUE THREAD

**Issue by ghost** [koktaildotcom/com.koktail.beacon#1]
I have a NUT beacon, it's recognized with the app and also paired (and usable in flows).

But after pairing the device gets status: undetected  while its 1 meter from the homey.

**Comment by koktaildotcom** [comment]
I think that the NUT beacon is going in powersave modus and is not publicly discoverable anymore. Cannot find any documentation about that beacon.

Can you try to add your phone as beacon and look if that has the same behaviour?

**Comment by ghost** [comment]
I got a iphone6S, with bluetooht on and detectable it is not seen as an beacon.

Could you maybe make a list of tested beacons ?

**Comment by koktaildotcom** [comment]
I found the issue, after pairing the beacon `detects` a change from `unknown` (null) to in/out range. Made a fix for it in next release. Iphone is not public detectable indeed.

**Comment by koktaildotcom** [comment]
resolved in https://github.com/koktaildotcom/com.koktail.beacon/releases/tag/1.0.5

**Comment by ghost** [comment]
installed the latest version 1.0.12 on the homey, added the NUT beacon.
recognized and detectable, after a few minutes it gets undetected. 

do you have a beacon that is fully supported?  (brand, type?)

**Comment by koktaildotcom** [comment]
I've bought some `Tile Pro` ble beacons after i used some nordicsemi nRF51822 from our chineese 
fellow man.

**Comment by ghost** [comment]
> I've bought some `Tile Pro` ble beacons after i used some nordicsemi nRF51822 from our chineese
> fellow man.

Got a tile pro myself now, when i make a flow 1 to detect the device and 1 flow when it's undetected it seems to be the same situation? when it's not detected and i press the button on the tile it's instantly detected. After a minute or so the tile it status "not detected"

-edit
nevermind, problem seems to have been solved. The Tile pro seems to work perfect.

**Comment by koktaildotcom** [comment]
Think the button will connect your phone to the Tile. And make your phone ring. If the BLE is connected to a service (phone) there isn't a broadcast anymore and the device is not seen by the app anymore.
