### ISSUE TITLE
Trigger beacon change doesnt work

### ISSUE THREAD

**Issue by marcelwolf** [koktaildotcom/com.koktail.beacon#10]
I am using a Tile mate. I noticed when i make a flow with ‘Beacon inside range’ of ‘Beacon outside range’ it works perfect.
However the flow ‘Beacon change’ doesn’t work. Nothing happens when the status changes.

App version 1.0.14
Homey verion : 1.5.13

**Comment by koktaildotcom** [comment]
This issue wil be fixed in 1.0.15 that is currently in `alpha`.
