### ISSUE TITLE
Unable to find any BLE device

### ISSUE THREAD

**Issue by Strike2001** [koktaildotcom/com.koktail.beacon#11]
when i try to add a new device as ibeacon the app find no devices and forces to close the window. 
app 1.0.14
homey latest beta firmware

**Comment by koktaildotcom** [comment]
Can you try again and send a log to the developer? 

In google chrome:
Goto: /manager/settings/#homey:manager:apps
Click one time inside the white “frame” with: Apps installed on Homey.
Hover the app: ‘homey-mi-flora’ with the <alt> key and wait until the ‘Send to developer’-button appear and click on it.

**Comment by Strike2001** [comment]
done , after update , and deinstall reinstall still not found any BLE device .

**Comment by koktaildotcom** [comment]
Have you send a log to the developer?

**Comment by Strike2001** [comment]
yes , i had send via the button , do make your app ready for v 2.0 ?

Von meinem iPhone gesendet

**Comment by koktaildotcom** [comment]
Try update the app to: `1.0.17` if there aren't any devices on pair send a log again please.
I'm currently working on migration to v2.0 but it is stuck on some issues from the BLE Homey core.

**Comment by koktaildotcom** [comment]
Is this issue same as: https://github.com/koktaildotcom/com.koktail.beacon/issues/12? Or is this resolved already?
