### ISSUE TITLE
Unable tot add TilePro (BLE core issue)

### ISSUE THREAD

**Issue by FrankRinkens** [koktaildotcom/com.koktail.beacon#12]
Hi I’m trying to install a Tile. Receive the pop up message: “Cannot get devices:No devices found”. Is this a know issue? 

Homey software version 2

Br Frank.

**Comment by koktaildotcom** [comment]
I did't encounter your issue before myself. What is your `updateInterval` setting? The app has to update the device list once to have some devices to pair in the list. I'll make a change for that because that is not desirable.

**Comment by FrankRinkens** [comment]
Hi, I use all the default settings and this is my first Beaon I want to install. Never used your software in previous versions of Homey.

in dutch:
Interval tussen updates: 10 sec
Ontdek timeout; 5 sec
Verificatie instellingen binnen bereik: 1
Verificatie instellingen buiten bereik: 5

Br Frank
![image1](https://user-images.githubusercontent.com/32610925/51164509-74cc7800-189d-11e9-9778-9739404fe87c.jpeg)

**Comment by koktaildotcom** [comment]
Wil you try the follow:
1. Change the `ontdek timeout` to 10 sec.
2. Reboot Homey.
3. Wait for all the devices to be ready.
4. Wait another 5 minutes.
5. Try to add a beacon again.

The app is not compatible with 2.0 due to Homey core BLE issues: https://github.com/athombv/homey-apps-sdk-issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+BLE

**Comment by FrankRinkens** [comment]
Hi, the changes are making no differents. The app isn't working correct at the moment.

**Comment by koktaildotcom** [comment]
Looks like there is something wrong with your BLE module. 
Can you send a report to the developer short after when this happend:

1. Goto: Apps.
2. Goto: App `Beacon`.
3. Click on settings icon (the cogwheel top right).
4. Click `send report to developer`.
5. Share the the log id with me.

**Comment by FrankRinkens** [comment]
I can do these steps, this afternoon/evening. Is it safe to post it in here?

**Comment by koktaildotcom** [comment]
> I can do these steps, this afternoon/evening. Is it safe to post it in here?

The log id isn't a security risk, you can PM me if you want.

**Comment by koktaildotcom** [comment]
What version are you on? Only the `alpha` version is compatible with v2.0 (and that does not work because of Homey core issues)

**Comment by koktaildotcom** [comment]
See https://github.com/koktaildotcom/com.koktail.beacon/issues/13

**Comment by FrankRinkens** [comment]
beacon v1.0.17
homey v2.02
app v2.0.6.250

**Comment by FrankRinkens** [comment]
I know it's a BLE issue. I have send an e-mail to Athom about this on Jan 23rd. 

Answer was they will solve it before end feb. If I have still issue in that moment of time I have to report a new ticket

**Comment by koktaildotcom** [comment]
Hopefully they will. I'll been waiting for this for months now. If they give time estimates the solutions is mostly close ;)

**Comment by FrankRinkens** [comment]
Or just a method to get rid of tickets ;), we will see.
