### ISSUE TITLE
Tile Mate does not pair Homey V2.0 (BLE core issue)

### ISSUE THREAD

**Issue by gewoondemax** [koktaildotcom/com.koktail.beacon#13]
After upgrade from 1.53 to Homey V2.0 the beacon app does not work anymore. Got 3 Tile Mate and only one is detected but does not in the flow. The other two are not to be detected or to pair with Homey

**Comment by koktaildotcom** [comment]
The app is not compatible with 2.0 because of Homey BLE core issues.

See: https://github.com/athombv/homey-apps-sdk-issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+ble

Are the `Tile mate` beacons not connceted to an other device?

**Comment by gewoondemax** [comment]
Hello that’s a bummer! 

No all Tile Mates were connected to Homey No other device.
Will there be another app? Or ... 

Thank you For your mail,
Regards

Max Mackenzie

Verstuurd vanaf mijn iPhone

**Comment by koktaildotcom** [comment]
I hope the Homey core issues wil be resolved soon. As they are fixed i'll update the app again offcorse.

**Comment by gewoondemax** [comment]
Ow That would be awesome …. but i guess  this issue is @ the end of their bucket list ..?

**Comment by gewoondemax** [comment]
Hi Leendert, You should now able to buy a Good Belgian beer :-) (maximacs paypal) are you aware of any progress on this? The app does not find any device and quits...

**Comment by koktaildotcom** [comment]
Thank you for you support, i've had carolus whisky infused yesterday. So that should worm ;)

On what version are you? 'stable' and 'beta' are not 2.0 compatibel het.

**Comment by gewoondemax** [comment]
Unfortunately on latest release V2.0 i would say cheers!

Verstuurd vanaf mijn iPhone

**Comment by koktaildotcom** [comment]
Ehat version of the beacon app?

Homey: v2.0.1 
Beacon app: ?

**Comment by gewoondemax** [comment]
The 1.0.17 For Beacon and V2.0.0 For Homey

Verstuurd vanaf mijn iPhone

**Comment by koktaildotcom** [comment]
1.0.17 is only compatible with < 2.x. If the core ble issues are solved i'll release an beta version.

**Comment by gewoondemax** [comment]
Hi Leendert, Athom did a change to 2.0.2 and according their release lot of things were improved on the Core ... maybe ... or is it not .. for the iBeacon ... I tried but have same issue when installing a device it tells cannot get devices: No devices found ... maybe BlueTooth not available @ Athom? or other way of pairing?
