### ISSUE TITLE
iTAG will not be detected

### ISSUE THREAD

**Issue by michapr** [koktaildotcom/com.koktail.beacon#15]
Hi,
I have 2 beacons type iTAG -it cannot be used.
What kind of information do you need for integration?

Advertising: type: legacy
Flags: LimitedDiscoverable, BrEdrNotSupported
Appearance: [961] Keyboard (HID subtype)

BTW: 
it have an additional "Immeddiate Alert" (0x182) with 
"Alert Level" (0x2A06)  -> write 0x00, 0x01, 0x02  +notify, write no response
and "unknown service" (0000ffe0) with
"unknown characteristic" (notify, read) 0x01 if pressed, 0x00 if "clean"

mobile Bluetooth scanner and nRF scaner can find it (and connect)

Thanks!
Michael

**Comment by koktaildotcom** [comment]
The app only needs a public discoverable uuid and name. This get polled every x seconds. If it does not exists in the list, it is marked outside range.

Sorry for the delay.
