### ISSUE TITLE
not compatible with Homey 1.5.3?

### ISSUE THREAD

**Issue by michapr** [koktaildotcom/com.koktail.beacon#16]
Cannot install the App - "incompatible with your Homey softare version"

What version will be needed as minimum? 
(maybe good idea to add it in description? Or I haven't seen it ;) )

Thanks!

**Comment by koktaildotcom** [comment]
This message is given by the app store. 1.5.3 has no BLE support.

Compatibility 1.5.8 to < 2.0 for now
