### ISSUE TITLE
Possible to implement Minew C6 Beacon

### ISSUE THREAD

**Issue by Tequila329** [koktaildotcom/com.koktail.beacon#19]
Hi, 

is it possible to implement the Minew C6 beacons to the beacon app? 
They are not found by homey/app. I used them before an a raspberry and they offer a real good detection radius. 

Thanks

**Comment by Tequila329** [comment]
Please set on hold, as i read, i will do a factory reset of the beacon in the evening. 
Will report in, if this fix the problem

**Comment by Tequila329** [comment]
No factory reset doesn’t change it.
Beacon is visible to other apps, they can see it and change beacon settings

**Comment by koktaildotcom** [comment]
What app version and Homey version?

**Comment by Tequila329** [comment]
oh, sorry, i forgot:

Homey: v2.0.5-rc.4
App: v 1.2.1

**Comment by koktaildotcom** [comment]
Can you try if v1.2.3 is released? I've made some adjustments at the discovery on pairing. The release is currently in review.

**Comment by Tequila329** [comment]
Sure, can i install it via CLI?

**Comment by koktaildotcom** [comment]
Yes, you can if you use branch 'feature/v2': `git checkout feature/v2`

**Comment by Tequila329** [comment]
Installed it, but unfortunately no beacons discovered. 

Beacons are this type: 
https://www.beaconshop24.de/minew-c6-en.html?language=en&switch_country=DE

Chipset is a Nordic nRF51822, so shouldn't be a problem?

**Comment by Tequila329** [comment]
Couldn't connect a Tile Pro either! 
Can find the mi flower sensors, lametric clocks, polar heartbeat devices, etc. 
Only beacons doesn't appear :( 
Should i create a diagnostic report?

**Comment by koktaildotcom** [comment]
Nordic nRF51822 will disable its discovery mode after some time.
