### ISSUE TITLE
TAG name in flow

### ISSUE THREAD

**Issue by dicknystrand** [koktaildotcom/com.koktail.beacon#22]
It's not possible to name/rename TAG for Beacon device. I'v renamed the device but tagname is still default Beacon 1.

**Comment by koktaildotcom** [comment]
`Beacon 1` is the example of a local tag. If you put it in a flow it will change to the one that is triggered.

**Comment by dicknystrand** [comment]
Sorry but when useing tag the name, Beacon 1 is the name presented not the name of the device.

**Comment by koktaildotcom** [comment]
Can you please describe the steps to reproduce?

**Comment by dicknystrand** [comment]
Hi

It’s working now whitout any changes.

Skickat från min iPad

**Comment by dicknystrand** [comment]
Hi 

After changing the flow tag stop working. 

Skickat från min iPad
