### ISSUE TITLE
Problems with Hue/Homey

### ISSUE THREAD

**Issue by HendrikjeVe** [koktaildotcom/com.koktail.beacon#26]
If have Hue installed on my Homey and it works without any problem. Now I have installed the beacon on my Homey and immidiatly the movement detectors of the Hue are getting a "!!" and I was getting trouble in reatching the Homey with my app on my Phone and tablet. When I removed the the beacon, all the problems where over. Can you help me with this because your beacon is one of a kind.

**Comment by tboudri** [comment]
I have the same issues. And besides Philips Hue not working correctly. Also Homey is not working correctly anymore. Everytime when Beacon is installed Homey app struggles to connect to homey. As soon as i remove beacon everything works as normal. After reinstalling beacon problems starts again.

I have used beacon version 1.2.9.  My Homey is a 2016 model

**Comment by koktaildotcom** [comment]
The polling of the beacons can be resource intensive to the 2016 model. I suggest to change to a polling interval for more than 30 seconds.

The BLE manager is still known to causes unstable reactions to Homey unfortunately.
