### ISSUE TITLE
Button action on a tile pro

### ISSUE THREAD

**Issue by kof** [koktaildotcom/com.koktail.beacon#27]
It would be nice to be able to use the tile pro button additionally. A good use case is to trigger the danalock action to open the door, so that beacon has a dual use.

**Comment by axelne** [comment]
I recently got the tile pro 2020. Cant get it to connect

**Comment by Goliath2000** [comment]
Same here I got the new tile pro 2020 and I can’t find it through the app from homey. 
It won’t detect it.

**Comment by axelne** [comment]
I read on some other forum that it wont sync to your homey once u synced it
to ur tile app. That kind of defears the purpose tho

Den tis 15 okt. 2019 18:56Goliath2000 <notifications@github.com> skrev:

**Comment by Goliath2000** [comment]
Don’t know if this is true, I have two tile pro and one is connected to Tile app but the other one was not synced with anything.

**Comment by Goliath2000** [comment]
I’m not sure if this is true! I bought two tile pro 2020 and one was synced with tile app but the other one was not synced. None of them was detected by beacon app from homey.

**Comment by Goliath2000** [comment]
I can find these tile pro beacons with my iPhone or iPad but they are not visible for homey. Must be something that makes them invisible for homey! Any ideas?

**Comment by Goliath2000** [comment]
> I recently got the tile pro 2020. Cant get it to connect

Have you been able to connect it with homey? Or still no luck?

**Comment by Zcooby** [comment]
Here the same problems. 
Homey cant connected to mine Tile pro 2020, have the tile working on the google app. 
You install the tile conform the instructions in the box ; download app> follow in app instruc. > Attach youre things. Then install to Homey but Homey do not see the tile. After that i gone look on github if there something wrong.

**Comment by EricvdP** [comment]
> I recently got the tile pro 2020. Cant get it to connect

Same here

**Comment by koktaildotcom** [comment]
Only discoverable BLE devices are supported in the app. The app does not connect to the device but only detects the beacon.
