### ISSUE TITLE
Polling tweak

### ISSUE THREAD

**Issue by ghost** [koktaildotcom/com.koktail.beacon#5]
Is there anyway to tweak the polling of the beacons in the app? or is this limited by Athom in the bluetooth chip?

Problem is that sometimes the beacon is detected when the distance to the homey is 10 meter (When the device has capability of 70+ meter).

**Comment by koktaildotcom** [comment]
The device is broadcasting a BLE signal. Homey can discover all broadcasted beacons. That way the beacon is in- or outside the range. 

The range is not limited by Homey but by the beacon and the signal strength and obstructions (like wall,  glass or person). 

I've found out the device 'Tile pro' has a stronger signal than the the cheap 'nrf51822'. The battery saving state can be a cause, that way the range is limited.

I have not tested if there is a difference in the discovery distance and the distance the BLE device can be reached by the native app (e.g. if you connect with it)

I think 70 meters range for a BLE keychain beacon is highly exorbitant. That would require a much higher amount of power. That way your battery wouldn't last a month imo.
