### ISSUE TITLE
Precense detection dropouts

### ISSUE THREAD

**Issue by Asinke** [koktaildotcom/com.koktail.beacon#6]
Thanks for making this superb app, it almost does what I want. The issue is that with the beacons well within range of homey (< 2m) detection intermittently fails. I have tested this with two beacon brands (Tile 'Joke'  and noname China 'iTAG' )both behaving the same. Looking at the timing could this be solved by adding a configurable retry period to to code before a declaring a tag offline?

See below a log I created:
2018-11-03 13:56:50 Joke detected
2018-11-03 13:56:10 Joke lost
2018-11-03 13:29:04 iTAG detected
2018-11-03 13:28:24 iTAG lost
2018-11-03 13:22:59 iTAG detected
2018-11-03 13:21:37 iTAG lost
2018-11-03 13:18:14 Joke detected
2018-11-03 13:17:33 Joke lost
2018-11-03 13:03:19 iTAG detected
2018-11-03 13:02:39 iTAG lost
2018-11-03 11:35:17 iTAG detected
2018-11-03 11:34:36 iTAG lost
2018-11-03 10:49:55 iTAG detected
2018-11-03 10:49:14 iTAG lost
2018-11-03 10:47:54 iTAG detected
2018-11-03 10:47:53 Joke detected
2018-11-03 10:47:12 iTAG lost
2018-11-03 10:47:12 Joke lost  

BTW. This log also show that the Tile performs better compared to the noName C tag.

Arthur

**Comment by koktaildotcom** [comment]
Wat version are you using? I've just released 1.0.13 beta tot the store. Is your ble beacon not connected tot another device?

**Comment by Asinke** [comment]
Was running stable version 1.0.3, upgraded to latest beta 1.0.13 now. Beacons are not connected to another app.
Will update tomorrow on stability with this beta version.

On 3 Nov 2018, at 19:40, koktaildotcom <notifications@github.com<mailto:notifications@github.com>> wrote:


Wat version are you using? I've just released 1.0.13 beta tot the store. Is your ble beacon not connected tot another device?

**Comment by Asinke** [comment]
No issues detected anymore with the beta version installed yesterday. Thanks for your excellent support and development!

On 3 Nov 2018, at 19:40, koktaildotcom <notifications@github.com<mailto:notifications@github.com>> wrote:


Wat version are you using? I've just released 1.0.13 beta tot the store. Is your ble beacon not connected tot another device?

**Comment by koktaildotcom** [comment]
Good to hear that. Happy tot help! Enjoy the app, and if you have feedback please tell me.

And if you are super happy, you can always buy me a beer ;)
