### ISSUE TITLE
Add Tag state changed to trigger

### ISSUE THREAD

**Issue by AdyRock** [koktaildotcom/com.koktail.beacon#8]
I have managed to pair the remote fobs from my Somfy One alarm and with the new settings page I have tuned it to be pretty good at detecting when each of us is home.
To simplify the flows so I only need one per person instead of two could you add a trigger card to notify when the tag state changes along with a true / false variable to specify if the tag was activated or deactivated. That way I can use a condition to to set the users presence to home else away.

**Comment by koktaildotcom** [comment]
This issue wil be fixed in 1.0.15 that is currently in `alpha`.
