### ISSUE TITLE
Unable to add additional beacons

### ISSUE THREAD

**Issue by Asinke** [koktaildotcom/com.koktail.beacon#9]

**Comment by koktaildotcom** [comment]
Can you be more specific about the issue you are reporting?

**Comment by Asinke** [comment]
I was preparing a bug report but decided not to submit.
When attempting to add a new iTAG, the setup wizard almost instantly returned stating:

Cannot get devices:No devices found.
You may close this window.

By making the device discovery before trying to add it worked out just fine. Hence I considered this a user error.

**Comment by koktaildotcom** [comment]
Good tot hear you find out. Have fun with the app. Will you rate the app if you have tested it complete?
